(module (scheme small) ()
        (import 
          (chicken module)

          (scheme base)
          (scheme case-lambda)
          (scheme char)
          (scheme complex)
          (scheme cxr)
          (scheme eval)
          (scheme file)
          (scheme inexact)
          (scheme lazy)
          (scheme load)
          (scheme process-context)
          (scheme r5rs)
          (scheme read)
          (scheme repl)
          (scheme time)
          (scheme write))

        (reexport
          (scheme time)
          (scheme base)
          (scheme case-lambda)
          (scheme char)
          (scheme complex)
          (scheme cxr)
          (scheme eval)
          (scheme file)
          (scheme inexact)
          (scheme lazy)
          (scheme load)
          (scheme process-context)
          (scheme r5rs)
          (scheme read)
          (scheme repl)
          (scheme time)
          (scheme write)
          ))

